package shared;

public enum Events {
    ZAKO_EXPLODED,
    BOSS_GALAGA_EXPLODED,
    GOEI_EXPLODED,
    NEXT_STAGE,
    CHALLENGING_STAGE,
    PLAYER_SHOOTING,
    COIN_SCREEN_OPENED,
    GAME_STARTED,
    BOSS_GALAGA_NOW_ONESHOT,
    ALIEN_DIVING,
    LIFE_LOST    
}
