# view values
VIEW_SCREEN_WIDTH=448
VIEW_SCREEN_HEIGHT=576

# model values
INITIAL_LIVES=3

# Cheats
CHEAT_GOD_MODE=false
CHEAT_INFINITE_LIVES=false
CHEAT_INFINITE_SHOTS=false
CHEAT_START_STAGE=1
CHEAT_NUKE_BUTTON=false